const endpoints = {
    baseUrlPublicacion: `http://localhost:5000/articulo`,
    baseUrlReferencia: `http://localhost:5000/referencia`,
    baseUrlBaseDatosDigital: `http://localhost:5000/baseDatosDigital`,
    baseUrlMedioPublicacion: `http://localhost:5000/medioPublicacion`,
    baseUrlMedioPublicacionBusqueda: `http://localhost:5000/medioPublicacionBusqueda`,
    baseUrlEstadisticasUso: `http://localhost:5000/estadisticasUso`,
    baseUrlEstadisticasJournal: `http://localhost:5000/estadisticasJournal`,
    baseUrlAreaUnesco: `http://localhost:5000/areaUnesco`,
    baseUrlAreaFrascati: `http://localhost:5000/areaFrascati`,
    baseUrlAreaSJR: `http://localhost:5000/areaSJR`,
    baseUrlAreaCategoriaSJR: `http://localhost:5000/areaCategoriaSJR`,
    baseUrlEquivalenciaAreaUnesco: `http://localhost:5000/equivalenciaAreaUnesco`,
    baseUrlEquivalenciaAreaUnescoFracati: `http://localhost:5000/equivalenciaAreaUnescoFrascati`,
    baseUrlCategoriasSJR: `http://localhost:5000/categoriasSJR`,
    baseUrlAutor: `http://localhost:5000/autor`,
    baseUrlArticuloAutor: `http://localhost:5000/articuloAutor`,
    baseUrlClustering: `http://localhost:5000/cluster`,
    baseUrlDetalleReferencia: `http://localhost:5000/detalleReferencia`,
    baseUrlLeyBradford: `http://localhost:5000/leyBradford`,
    baseUrlAnalisisEstadistico: `http://localhost:5000/analisisEstadistico`,
    baseUrlMedioPublicacionPublicacion: `http://localhost:5000/medioPublicacionPublicacion`,
    baseUrlMedioPublicacionCitacion: `http://localhost:5000/medioPublicacionCitacion`,
    baseUrlResumenMedioPublicacion: `http://localhost:5000/resumenMediosPublicacion`,
    baseUrlSJR: `http://localhost:5000/sjr`,
    baseUrlJournal: `http://localhost:5000/journal`,
    baseUrlParametro: `http://localhost:5000/parametro`
}
export default endpoints;

